server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    discovery-client-enabled: true
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.131.128:9200
  jackson:
    default-property-inclusion: non_null #默认属性包含，non_null表示空的字段不显示在jackson数据中
  thymeleaf:
    cache: false #关闭缓存
feign:
  sentinel:
    enabled: true

