server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        - id: index-route #同步请求路由
          uri: lb://index-service
          predicates:
            - Host=gmall.com,www.gmall.com
            #- 如果再加入一个路由，默认是and关系
          filters:
            - AddResponseHeader=xxx,yyy
            - Auth=/xxx
        - id: index-route2 #异步请求路由，只能通过路径方式路由（鼠标点在一级标题上，查询二级三级分类）
          uri: lb://index-service
          predicates:
            - Path=/index/** #需要配置两个路由
        - id: item-route
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
        - id: cart-route
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
jwt:
  pubFilePath: D:\project-0108\rsa\rsa.pub
  cookieName: GMALL-TOKEN
  token: unick
