server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    discovery-client-enabled: true
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false #关闭缓存
feign:
  sentinel:
    enabled: true
thread:
  pool:
    corePoolSize: 500 #核心线程数
    maximumPoolSize: 1000 #最大可扩展线程数
    keepAlive: 60 #生存时间
    blockingSize: 500 #阻塞队列大小


