server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    discovery-client-enabled: true
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false #关闭缓存
feign:
  sentinel:
    enabled: true
jwt:
  pubFilePath: D:\project-0108\rsa\rsa.pub
  priFilePath: D:\project-0108\rsa\rsa.pri
  secret: 234 #最好定期修改
  expire: 300 #分钟
  cookieName: GMALL-TOKEN
  unick: unick

