server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  zipkin:
    discovery-client-enabled: true
    base-url: http://localhost:9411
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/guli_ums
  redis:
    port: 6379
    host: 192.168.131.128
  sleuth:
    sampler:
      probability: 1
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.ums.api.entity
logging:
  level:
    com.atguigu.gmall: debug
